//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LolAnimationChanger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LolAnimationChanger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidewinder94.
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/sidewinder94.
        /// </summary>
        public static string EditorUrl {
            get {
                return ResourceManager.GetString("EditorUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lol-animation-changer.zarrouk.eu.
        /// </summary>
        public static string GATrackingDomain {
            get {
                return ResourceManager.GetString("GATrackingDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UA-55920654-2.
        /// </summary>
        public static string GATrackingId {
            get {
                return ResourceManager.GetString("GATrackingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://raw.githubusercontent.com/sidewinder94/LolAnimationChanger/master/LICENSE.
        /// </summary>
        public static string LicenseUrl {
            get {
                return ResourceManager.GetString("LicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manifest.json.
        /// </summary>
        public static string ManifestName {
            get {
                return ResourceManager.GetString("ManifestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RADS\projects\lol_air_client\releases\.
        /// </summary>
        public static string ReleasesPath {
            get {
                return ResourceManager.GetString("ReleasesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://data.zarrouk.eu/lol-animation-changer/.
        /// </summary>
        public static string RootAddress {
            get {
                return ResourceManager.GetString("RootAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/sidewinder94/LolAnimationChanger.
        /// </summary>
        public static string SourceUrl {
            get {
                return ResourceManager.GetString("SourceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RADS\projects\lol_air_client\releases\{0}\deploy\theme.properties.
        /// </summary>
        public static string ThemeConfigFile {
            get {
                return ResourceManager.GetString("ThemeConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RADS\projects\lol_air_client\releases\{0}\deploy\mod\lgn\themes\.
        /// </summary>
        public static string ThemeDirPath {
            get {
                return ResourceManager.GetString("ThemeDirPath", resourceCulture);
            }
        }
    }
}
